[dev]
  port = 8888
  envFiles = [".env"]

[build]
  publish = "dist"          # Or "public", or "" if root is used
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"  # Required for ES modules (like your `export async function handler`)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200